### ISSUE TITLE
Feature request: Count occurrences of `\n` and `\r\n` to get the line number

### ISSUE THREAD

**Issue by fschutt** [RazrFalcon/simplecss#1]
In error messages I'd like to print the line number of where the error occurred in the error message. Right now, all I can print is the `pos()`, which just gives me the number of characters from the start, which isn't very useful. It would be great if the `Tokenizer` could sort-of update a certain state once it sees a line break, so I can get the `line()`, `column()` number for error reporting (like serde-json, for example).

**Comment by RazrFalcon** [comment]
There is `Stream::gen_error_pos`.

You can use it like (not sure if it will run):
```rust
let mut s = Stream::new(b"text");
s.advance(2);
println!("{:?}", s.gen_error_pos());
```

This project wasn't updated for two years and should be rewritten. So does not expect mush from it.

**Comment by RazrFalcon** [comment]
Should we close it now?

**Comment by fschutt** [comment]
Maybe I'll try writing a PR for it if I absolutely need it... I'll close this issue until then.
