### ISSUE TITLE
Get list of classes as they appear in stylesheet

### ISSUE THREAD

**Issue by praveenperera** [RazrFalcon/simplecss#4]
If I have a css file `index.css` and I wanted to get a list of all the classes as they appear in the file how would I do that?

I am able to get a list of rules and selectors but how can I get the class name of each selector?

**Comment by RazrFalcon** [comment]
Hi. It's not possible. `simplecss` designed just for style matching.

**Comment by praveenperera** [comment]
Ah okay thanks, if possible could you point me in the right direction to do that?

**Comment by RazrFalcon** [comment]
I guess you can use [cssparser](https://crates.io/crates/cssparser), but it's pretty heavy and low-level.

On the other hand, you can simply fork `simplecss` and make `Selector`'s [internals](https://github.com/RazrFalcon/simplecss/blob/01fab2f637e66be96d13816a3e3be8c030c71e00/src/selector.rs#L138) public. The main problem is that `simplecss` stores a selector as an AST and *class selectors* are converted/desugared into `[style~=value]`.
